# Generated by Django 3.2.8 on 2021-10-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not to', 'Prefer Not to')], max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('path', models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End'), ('Data Analys', 'Data Analys'), ('Data Science', 'Data Science'), ('AWS-DevOps', 'AWS-DevOps')], max_length=50)),
            ],
        ),
    ]
